const tintColorLight = '#1D6FF2';
const tintColorDark = '#4D96FF';

export default {
  light: {
    primary: '#1D6FF2',
    primaryLight: '#E6F0FF',
    secondary: '#6366F1',
    success: '#22C55E',
    successLight: '#DCFCE7',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    text: '#1F2937',
    textSecondary: '#4B5563',
    textTertiary: '#9CA3AF',
    background: '#FFFFFF',
    backgroundSecondary: '#F9FAFB',
    card: '#FFFFFF',
    border: '#E5E7EB',
    tint: tintColorLight,
    tabIconDefault: '#9CA3AF',
    tabIconSelected: tintColorLight,
  },
  dark: {
    primary: '#4D96FF',
    primaryLight: '#1E3A8A',
    secondary: '#818CF8',
    success: '#4ADE80',
    successLight: '#065F46',
    warning: '#FBBF24',
    warningLight: '#78350F',
    error: '#F87171',
    errorLight: '#7F1D1D',
    text: '#F9FAFB',
    textSecondary: '#E5E7EB',
    textTertiary: '#9CA3AF',
    background: '#111827',
    backgroundSecondary: '#1F2937',
    card: '#1F2937',
    border: '#374151',
    tint: tintColorDark,
    tabIconDefault: '#6B7280',
    tabIconSelected: tintColorDark,
  },
};